### ISSUE TITLE
firefox - Piece of puzzle

### ISSUE THREAD

**Issue by nasser89** [ArgoZhang/SliderCaptcha#1]
hi 
in fire fox the Piece of puzzle you got to drag become square instead of puzzle shape

**Comment by ArgoZhang** [comment]
windows or macos? and version

**Comment by ArgoZhang** [comment]
ok. I had repo this issue. will fixed later. thank you. :smile:

**Comment by ArgoZhang** [comment]
@nasser89 I have pushed a commit 315bf9d to fix this issue. please  let me know how that works.

**Comment by nasser89** [comment]
hi , sorry for delay i just notice it now , it is on windows firefox quantum 67.0.1 (64-bit),
i will check and respond in 4 hour , just have a task to do 
by the way its really cool captcha 
cheers

**Comment by nasser89** [comment]
hello mr zhang ,i must apologize for this late respond totally forget to check it and today when i was checking github i saw the issue

**Comment by nasser89** [comment]
i have checked both firefox and chrome and it work like a charm
