### ISSUE TITLE
这个插件服务端验证安全么？

### ISSUE THREAD

**Issue by John0King** [ArgoZhang/SliderCaptcha#13]
没看明白怎么验证的

**Comment by diyews** [comment]
看起来是计算客户端传过来的拖动时 Y 轴抖动值的方差，人工的话方差基本都不会是 0 ，毕竟手抖

**Comment by ArgoZhang** [comment]
@diyews 太对了。就是这样的。可以自己设计验证数学模型。我只是抛砖引玉而已
